/**
 * Storage, on D1 (§8).
 *
 * Every access in this file is by primary key. The service has no list route —
 * the catalogue is a static file regenerated by the weekly build — so the
 * ordering guards that made the Fastify version's `ORDER BY` clauses
 * load-bearing have no counterpart here: there is no sequence in which this
 * service returns entries, and therefore no sequence through which per-entry
 * provenance could leak.
 *
 * The synthetic flag and the automation likelihood are still stored and still
 * aggregate-only. Nothing in this file returns either one, and `publicEntry`
 * remains the single shape an entry leaves the service in.
 */

import { sha256 } from '@wearme/core/hash';
import type { AttrVector, Identity } from '@wearme/core/types';

export interface Row {
  id: string;
  attrs: string;
  created_at: string;
  wear_count: number;
  synthetic: number;
  automation: number | null;
  revocation_hash: string | null;
}

export const today = (): string => new Date().toISOString().slice(0, 10);

/**
 * The only shape an entry leaves the service in.
 *
 * Neither the visitor nor the artist can tell a manufactured entry from a
 * donated one by looking, because the field that would say so is not in the
 * object and is not derivable from it.
 */
export function publicEntry(row: Row): Identity {
  return {
    id: row.id,
    attrs: JSON.parse(row.attrs) as AttrVector,
    createdAt: row.created_at,
    wearCount: row.wear_count,
  };
}

export function hashToken(token: string): string {
  return sha256(`revocation:${token}`);
}

export async function findIdentity(db: D1Database, id: string): Promise<Row | null> {
  return db.prepare('SELECT * FROM identity WHERE id = ?').bind(id).first<Row>();
}

/** Present-or-not, without reading the attribute vector back to answer it. */
export async function identityExists(db: D1Database, id: string): Promise<boolean> {
  const row = await db.prepare('SELECT 1 AS present FROM identity WHERE id = ?').bind(id).first();
  return row !== null;
}

export async function insertIdentity(
  db: D1Database,
  entry: { id: string; attrs: AttrVector; automation: number | null; revocationHash: string },
): Promise<void> {
  await db
    .prepare(
      `INSERT INTO identity (id, attrs, created_at, wear_count, synthetic, automation, revocation_hash)
       VALUES (?, ?, ?, 0, 0, ?, ?)`,
    )
    .bind(entry.id, JSON.stringify(entry.attrs), today(), entry.automation, entry.revocationHash)
    .run();
}

/**
 * Withdrawal.
 *
 * The entry is deleted and its id is written to `revoked` in one batch, so
 * there is no interval in which it is gone from the pool but still absent from
 * the list the catalogue filters against. A donor who withdraws gets both
 * effects or neither.
 */
export async function revokeIdentity(db: D1Database, id: string): Promise<void> {
  await db.batch([
    db.prepare('DELETE FROM identity WHERE id = ?').bind(id),
    db.prepare('INSERT OR REPLACE INTO revoked (id, revoked_at) VALUES (?, ?)').bind(id, today()),
  ]);
}

/** Returns the new count, or null when no such entry exists. */
export async function countWear(db: D1Database, id: string): Promise<number | null> {
  const row = await db
    .prepare('UPDATE identity SET wear_count = wear_count + 1 WHERE id = ? RETURNING wear_count')
    .bind(id)
    .first<{ wear_count: number }>();
  return row?.wear_count ?? null;
}

export async function readWearCount(db: D1Database, id: string): Promise<number | null> {
  const row = await db
    .prepare('SELECT wear_count FROM identity WHERE id = ?')
    .bind(id)
    .first<{ wear_count: number }>();
  return row?.wear_count ?? null;
}

/**
 * The ids withdrawn since the last catalogue rebuild.
 *
 * Short by construction: the weekly build empties this table once the
 * regenerated catalogue no longer lists the entries, so it holds one week of
 * withdrawals at most and usually nothing.
 */
export async function listRevoked(db: D1Database): Promise<string[]> {
  const { results } = await db.prepare('SELECT id FROM revoked').all<{ id: string }>();
  return results.map((r) => r.id);
}
