/**
 * Generates the D1 seed from the launch pool.
 *
 *   npm run seed:build --workspace @wearme/worker
 *
 * The 200 launch entries are synthetic and already committed, in full, as
 * `data/bootstrap.json`. Emitting them as SQL produces roughly 600KB of INSERT
 * statements that say nothing the JSON does not already say, so the output is
 * generated on demand and git-ignored rather than committed twice in two
 * formats that could drift apart.
 *
 * This replaces `seedFromBootstrap` in the Fastify service, which ran a
 * COUNT(*) against the pool on every cold boot to decide whether to seed. A
 * Worker cold-boots far more often than a long-lived process, and the check
 * would have cost a database round trip on requests that never needed one.
 * Seeding is a deploy-time act, so it happens at deploy time.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { AttrVector } from '@wearme/core/types';

const here = dirname(fileURLToPath(import.meta.url));
const poolPath = resolve(here, '../../../data/bootstrap.json');
const outPath = resolve(here, '../seed/0002_launch_pool.sql');

interface BootstrapFile {
  syntheticAtLaunch: number;
  entries: { id: string; attrs: AttrVector; createdAt: string; automation: number }[];
}

/** SQLite string literal. Doubling the quote is the whole of the escaping rule. */
const quote = (value: string): string => `'${value.replace(/'/g, "''")}'`;

const file = JSON.parse(readFileSync(poolPath, 'utf8')) as BootstrapFile;

// Chunked so no single statement grows to hundreds of kilobytes. D1 accepts
// large imports, but a statement that cannot be read in a terminal cannot be
// debugged in one either.
const CHUNK = 25;
const lines: string[] = [
  '-- Generated by scripts/build-seed.ts from data/bootstrap.json. Do not edit.',
  `-- ${file.entries.length} synthetic entries, the pool as it stood at launch.`,
  '',
];

for (let i = 0; i < file.entries.length; i += CHUNK) {
  const rows = file.entries.slice(i, i + CHUNK).map((entry) => {
    // synthetic = 1 and revocation_hash = NULL: a manufactured entry has no
    // donor, so there is nobody who could withdraw it and no token to hold.
    const attrs = quote(JSON.stringify(entry.attrs));
    return `  (${quote(entry.id)}, ${attrs}, ${quote(entry.createdAt)}, 0, 1, ${entry.automation}, NULL)`;
  });
  lines.push(
    'INSERT OR IGNORE INTO identity (id, attrs, created_at, wear_count, synthetic, automation, revocation_hash) VALUES',
    `${rows.join(',\n')};`,
    '',
  );
}

// Recorded so the interface can state how many entries were synthetic at launch
// even after the pool has grown past them.
lines.push(
  `INSERT OR REPLACE INTO meta (key, value) VALUES ('syntheticAtLaunch', ${quote(String(file.syntheticAtLaunch))});`,
  '',
);

const sql = lines.join('\n');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, sql, 'utf8');

console.log(
  `wrote ${outPath}\n  ${file.entries.length} entries, ${(sql.length / 1024).toFixed(0)}KB\n` +
    `  apply with: npx wrangler d1 execute wear-me-pool --remote --file seed/0002_launch_pool.sql`,
);
