-- The pool, on D1 (§8).
--
-- The `identity` and `meta` tables are carried over from the SQLite schema
-- unchanged: same columns, same defaults, same absences. Stored is the
-- attribute vector, the derived id, a created-at bucketed to the day, the wear
-- count, the synthetic flag, the automation likelihood, and a hash of the
-- revocation token. Never stored: IP address, User-Agent, any request-level
-- identifier, any cookie. There is no column for them, which is a stronger
-- guarantee than a policy about them.
--
-- Two tables from the Fastify schema are deliberately absent. `report` and
-- `consequence` back SPEC §7 and §7b, both of which are still deferred; there
-- is no route that writes to them, so there is no table. They come back with
-- the features, not before.
--
-- Two indexes are also gone. `identity_created` and `identity_worn` existed to
-- serve ORDER BY in the list route, and this service has no list route: the
-- catalogue is published as a static file and regenerated by the weekly build.
-- Every identity access here is by primary key.

CREATE TABLE IF NOT EXISTS identity (
  id              TEXT PRIMARY KEY,
  attrs           TEXT NOT NULL,
  created_at      TEXT NOT NULL,
  wear_count      INTEGER NOT NULL DEFAULT 0,
  synthetic       INTEGER NOT NULL DEFAULT 0,
  automation      REAL,
  revocation_hash TEXT
);

CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Revocation, in the window before the catalogue is rebuilt.
--
-- Withdrawing an identity must remove it from the catalogue, and the catalogue
-- is a static file that only changes when the weekly build runs. Without this
-- table a revoked entry would stay on display for up to seven days, which is
-- not what the donor was promised. The site reads this list on load and filters
-- against it, so the removal is immediate even though the file is not.
--
-- Holding an id here says only that this id — already public, already in the
-- catalogue — was withdrawn. It is not linked to a person, a session, or an
-- address, because none of those exist anywhere in this schema. The weekly
-- build empties the table once the regenerated catalogue no longer lists the
-- entry, so the disclosure lasts days rather than permanently.
CREATE TABLE IF NOT EXISTS revoked (
  id         TEXT PRIMARY KEY,
  revoked_at TEXT NOT NULL
);

-- Rate limiting without keeping an address (§8).
--
-- The key is sha256(salt | bucket | address), where the salt is derived from
-- the current ten-minute epoch and a secret that never leaves the Worker. When
-- the epoch turns the salt changes, and every row already written becomes
-- unlinkable to any address — including to itself a minute earlier. Nothing
-- here can be correlated, subpoenaed or leaked back to a caller, because the
-- address was destroyed before the row was written.
--
-- The Fastify version kept this in process memory, which a Worker does not
-- have. Rows are pruned on write rather than on a timer, for the same reason.
CREATE TABLE IF NOT EXISTS ratelimit (
  key        TEXT PRIMARY KEY,
  count      INTEGER NOT NULL,
  expires_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS ratelimit_expiry ON ratelimit (expires_at);
